buildscript {
    ext {
        kotlin_version = '2.2.21'
        compose_version = '1.2.0-alpha02'
        core_ktx_version = '1.7.0'
        material_version = '1.4.0'
        activity_compose_version = '1.4.0'
        gradle_plugin_version = '8.13.1'
        mockito_version = '5.20.0'
        mockito_inline_version = '5.2.0'
        junit_version = '4.13.2'
        accompanist_version = '0.20.3'
        exoplayer_version = '2.16.1'
        coil_version = '1.4.0'
        navigation_version = '2.4.0-rc01'
        compose_gradle_plugin_version = '2.2.21'
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$gradle_plugin_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin:$compose_gradle_plugin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}